### ISSUE TITLE
Add option for turning off pixel fallback for font mixin.

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/tools.mixins#6]
Now that rem unit is [supported in all major browsers](http://caniuse.com/#search=rem) it would be good to add option to turn off pixel fallback. 

I would actually consider making pixel fallback off by default. It's 2015 :)

@csswizardry @csshugs @florianbouvot @anselmh what you guys think?

**Comment by anselmh** [comment]
I’m against it as Opera Mini hasn’t switched on `rem` support in their engine and IE8 still needs to be supported by many projects. Therefore I’d like to keep it on until at least Opera Mini supports it.

**Comment by florianbouvot** [comment]
@nenadjelovac :+1: pixel fallback off by default.

On last project we drop IE8 support and statistics (for redesign) shows that Opera Mini is not present in client's audience.

And if necessary we can turn pixel fallback on ;)

**Comment by anselmh** [comment]
Okay it makes sense to make this optional and offer a config flag to turn it on/off.

**Comment by csshugs** [comment]
:+1:

**Comment by nenadjelovac** [comment]
> I’m against it as Opera Mini hasn’t switched on rem support in their engine and IE8 still needs to be supported by many projects. Therefore I’d like to keep it on until at least Opera Mini supports it.

Yeah, I might be pushing it too far in terms of framework (better to support as many browser versions it can) :) 

But I think we all agreed we could benefit from it. I assume it should be a global variable in `_settings.defaults.scss` (eg. `$inuit-pixel-fallback`)?

**Comment by csshugs** [comment]
@nenadjelovac I really like the idea. Don't know what @csswizardry thinks about it in terms of adding complexity to the framework. But if you decide not to support IE8 and Opera Mini in your proect, the CSS output would definitely benefit from that variable.

**Comment by csshugs** [comment]
Opera Mini [is now on board](http://caniuse.com/#search=rem).

**Comment by florianbouvot** [comment]
@csshugs Good news, I'm in favor of adding this option

**Comment by florianbouvot** [comment]
@nenadjelovac close because it's ok in [new inuitcss version](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.mixins.scss#L24-L26)
